### ISSUE TITLE
Is bwoken supporting Xcode 4.4?

### ISSUE THREAD

**Issue by nov** [bendyworks/bwoken#11]
I got this error when running tests on device

```
Exception   encountered during 'setThrottleConstraints:' dispatch: (null)
```

and this error on simulator.

```
xcodebuild: error: 'sim' not found.
xcrun: error: /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild failed with exit code 17664
1.339582  handled [c0]: < DTXMessage 0x7f9da36a8c60 : i1.0 c0 dispatch:[agentIsReady] >
1.340150  sending [c0]: < DTXMessage 0x7f9da36aa140 : i1.1 c0 >
1.349105  handled [c0]: < DTXMessage 0x7f9da36aa2f0 : i2.0 c0 dispatch:[updateScriptStatus:[1]] >
1.349543  sending [c0]: < DTXMessage 0x7f9da3763bf0 : i2.1 c0 >
1.351177  sending [c0]: < DTXMessage 0x7f9da36ab730 : i3.0 c0 dispatch:[startScriptWithInfo:< NSDictionary 0x7f9da36aca60 | 3 key/value pairs>] >
1.358965  handled [c0]: < DTXMessage 0x7f9da36ac800 : i3.1 c0 object:(NSNull*)[<null>] >
1.368855  handled [c0]: < DTXMessage 0x7f9da3440f10 : i4.0 c0 dispatch:[updateScriptStatus:[2]] >
1.369123  sending [c0]: < DTXMessage 0x7f9da374e780 : i4.1 c0 >
1.379418  handled [c0]: < DTXMessage 0x7f9da36a4ce0 : i5.0 c0 dispatch:[scriptDidThrowException:< NSDictionary 0x7f9da36ab810 | 3 key/value pairs>] >
1.379867  sending [c0]: < DTXMessage 0x7f9da36aad80 : i5.0 c0 dispatch:[stopScript] >
1.380970  handled [c0]: < DTXMessage 0x7f9da36ad1c0 : i6.0 c0 dispatch:[updateScriptStatus:[1]] >
1.389602  handled [c0]: < DTXMessage 0x7f9da3763bf0 : i5.1 c0 object:(NSNull*)[<null>] >
1.497598  handled [c0]: < DTXMessage : kDTXInterruptionMessage >
1.497767  handled [c0]: < DTXMessage : kDTXInterruptionMessage >
```

**Comment by listrophy** [comment]
Please re-run with `rake --trace` and post the trace. Unfortunately, I can't replicate the issue.

Thanks!

**Comment by nov** [comment]
Sorry, it was because I had been using iOS6 with Xcode 4.4
Now I switched to Xcode 4.5 DP4 with recent @wbyoung's changes and bwoken works fine.

Thanks

**Comment by tcoulter** [comment]
@nov @listrophy @wbyoung - Unrelated to bwoken, we're receiving these DTX messages, specifically the same messages as above, in our project; in some cases, instruments hangs and stops the script from running. You're all I could find on Google. Do you know of any fix or workaround for this? From the conversation above, it sounds like XCode 4.5 may be the solution, though any information on XCode 4.4 is much appreciated. 

Thanks!

**Comment by listrophy** [comment]
I'd venture to guess that the DTX messages are independent of instruments hanging.

For me, the most often reason instruments seems to hang is that there's an OS X system-level pop-under requesting your password to continue.
