### ISSUE TITLE
Instruments Usage Error

### ISSUE THREAD

**Issue by Snekatis** [bendyworks/bwoken#13]
I have problem with using bwoken. 
When I use "rake" command after installation of bwoken, this text is displayed in the terminal: 

Instruments Usage Error : The specified template 'file://localhost/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Instruments/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate' does not exist.
instruments, version 4.5 (4523)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]

I am using:
bwoken 1.1.0
ruby 1.9.3 (using rvm)
Xcode 4.5 (4G182) (with command line tools installed)
Mac OS X 10.8.2

Do you have a solution for this, please?

**Comment by Jaym3s** [comment]
the path
'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Instruments'
does not exist on my machine (recently updated to Xcode 4.5). It looks like
bwoken is trying to find something that no longer exists or has been moved.
 I'll have time to look into it further on friday.

**Comment by seeker12** [comment]
I believe Xcode 4.5 breaks this. The full path to Instruments template is now:
"/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate"

The xcode-select -print-path method /Applications/Xcode.app/Contents/Developer is now apparently problematic.

**Comment by listrophy** [comment]
@seeker12 are you using bwoken 1.1.1? It was released this Tuesday.

**Comment by listrophy** [comment]
@seeker12 I know it's been quite some time, but do you have an update you could provide for this issue?

**Comment by listrophy** [comment]
Closed since I haven't heard back. Please reopen if you're still encountering this error. Thanks!
