### ISSUE TITLE
Any good examples?

### ISSUE THREAD

**Issue by trandoanhung1991** [bendyworks/bwoken#15]
Hi, I installed Bwoken because it seems pretty cool and fits my needs.

Problem is that I'm not sure where to start. Do you guys have any examples?

Specifically, I'm looking for ones that uses CoffeeScript, and has classes and extends.

**Comment by prolificcoder** [comment]
https://github.com/bendyworks/TravisCI.app This is a good sample. I am still trying to dissect and run it but this should get you started.
