### ISSUE TITLE
Bwoken configuration build directory does not play well with iPad only apps. 

### ISSUE THREAD

**Issue by prolificcoder** [bendyworks/bwoken#17]
Our iPad only app doesn't create the following build/iphonesimulator folder 
BWOKEN_CONFIGURATION_BUILD_DIR = <path to workspace>/build/iphonesimulator

and hence I am following error 
Check dependencies
No architectures to compile for (ARCHS=i386, VALID_ARCHS=armv7)

**Comment by ntodd** [comment]
This is a pretty easy fix and isn't an issue with Bwoken.  Change the "Build Active Architecture Only" setting in your build settings to "NO" for debug.

I suggest that `ONLY_ACTIVE_ARCH=NO` be added to the bwoken env_variables.

**Comment by listrophy** [comment]
Fixed in v1.2.1. See d70bd4b769705835ebc8735068a8b3f7d6e0b42d
