### ISSUE TITLE
Installation instructions outdated, don't work

### ISSUE THREAD

**Issue by gperks** [bendyworks/bwoken#28]
That, or I'm doing it wrong :)
1. After creating the .rvmrc, the instructions say to '. .rvmrc'. Up pops a warning "You are using '.rvmrc', it requires trusting, it is slower and it is not compatible with other ruby managers..."

It suggests running 'rvm rvmrc to .ruby-version', which I did. OK.
1. Later on after creating the Gemfile, the instructions say to 'rake bwoken:init'. Unfortunately that results in:
   > rake aborted!
   > cannot load such file -- bwoken/tasks

Unsure how to proceed here.

(Ruby version is 1.9.3-p429)

**Comment by listrophy** [comment]
Hmmm... on point number 1, I'll have to update the documentation. RVM has recently deprecated the `.rvmrc` file in favor of `.ruby-version` and `.ruby-gemset` files.

Do you now have a `.ruby-gemset` file in addition to `.ruby-version`?

**Comment by listrophy** [comment]
Documentation updated in 563baff56ca2f8e4c4ed1f46cf62693d1ef678ac and 75db7124355a15b2765c6f048ae49c3b534c2ea0

**Comment by gperks** [comment]
Thanks for the update!  I've now got further along. I followed all the bundler steps inside my .xcproject folder, up to and including the `rake bwoken:init`. 

Now I type 'rake' from within the .xcproject folder and it says:
  `xcodebuild: error: The workspace 'MyApp' does not contain a scheme named 'project'.`

I'm using a .xcworkspace (via cocoapods). Should I be performing the Bwoken install steps inside there instead of inside the project file?

**Comment by ryanjm** [comment]
@gperks - did you ever get your issue resolved?

You should be doing the install in the root directory of your project, not within the project file. The instructions are a little confusing on that point but the idea is that you'll see the project file in the current directory (not be inside of it).

**Comment by gperks** [comment]
I moved jobs and so this is no longer an issue - for me at least :)  Thanks for the help.
