### ISSUE TITLE
Remove colorful formatter for Jenkins

### ISSUE THREAD

**Issue by tobi512** [bendyworks/bwoken#32]
Hi guys, 
just another question regarding continuous integration:

By default bwoken uses the colorful formatter which is really nice!
However if you run your tests with bwoken on jenkins, the console can't handle the colorful highlighting and it looks like this:

[34mBuilding[m[34m.[m[34m.[m[34m.[m[34m.[m[34m.[m[34m.[m[34m.[m[34m.[m[34m.[m[34m.[m[34m.[m
[32mBuild Successful![m

[36mipad   Testscript.js[m
[36mStart:[m  Testscript
[36mDefault:[m    I'm an iPad Simulator
[36mDebug:[m  [33mtap[m toolbar.buttons[[35m"Show menu"[m]
[36mDebug:[m  [33mtap[m popover.actionSheet.buttons[[35m"Settings"[m]
[36mDebug:[m  [33mtap[m tableViews[[35m"Empty list"[m].cells[[35m"Something"[m]
[36mDebug:[m  [33mtap[m tableViews[[35m"Empty list"[m].cells[[35m"Test"[m].textFields[0]
[36mDebug:[m  [33mtap[m tableViews[[35m"Empty list"[m].cells[[35m"Test"[m].textFields[0].buttons[[35m"Clear text"[m]
[36mDebug:[m  keyboard.typeString("default")
[36mDebug:[m  [33mtap[m tableViews[[35m"Empty list"[m].cells[[35m"Test2"[m].textFields[0]
[36mDebug:[m  [33mtap[m tableViews[[35m"Empty list"[m].cells[[35m"Test2"[m].textFields[0].buttons[[35m"Clear text"[m]
[36mDebug:[m  keyboard.typeString("address")
[36mDebug:[m  [33mtap[m navigationBar.leftButton
[36mDebug:[m  [33mtap[m navigationBar.leftButton
[32mPass:[m   Testscript

[32mComplete[m
 Duration: [4;1m27.359995s[m

So, is there an easy option to disable the colorful formatting for this configuration?

Thanks!

**Comment by listrophy** [comment]
@tobi512 Thanks for taking the time to report this issue. In the next release, I'm planning to provide this functionality through a configuration flag. It will be something along the lines of `bwoken --formatter=passthru`.

 This is essentially a duplicate bug of #22, so I'm going to close this.

**Comment by tobi512** [comment]
Thanks for your fast answer!
I read through the issue list before posting, but didn't find a connection between my problem and the title of issue #22 
After reading it in detail, I completely agree with you.
