### ISSUE TITLE
Does Bwoken play well with CocoaPods?

### ISSUE THREAD

**Issue by michaelforrest** [bendyworks/bwoken#38]
I ask because my build fails on 

```
ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This could be because bwoken wants to build my .xcodeproj instead of my .xcworkspace, or it could be something idiosyncratic to my machine. I'm not sure where to look for guidance on this sort of thing, or how much it is to do with bwoken itself.

**Comment by michaelforrest** [comment]
Looking through closed issues it's pretty clear that this is a "YES, IT SHOULD". But not sure what to do about my problem here.

**Comment by listrophy** [comment]
@michaelforrest almost every time I think bwoken has screwed up compilation, it ends up being an actual syntax error in my project.

That said, that's an interesting linking error. Not sure what would have caused it. :(

**Comment by michaelforrest** [comment]
I managed to resolve this in the end by putting `gem 'cocoapods'` in my Gemfile, running bundle, then doing `pod install`. Once I was up to the latest version of everything it seemed better. 

I have other issues now but this particular one seems fixed.
