### ISSUE TITLE
Simulator is not launched automatically

### ISSUE THREAD

**Issue by Snekatis** [bendyworks/bwoken#4]
Hey,
I got very strange issue with bwoken, that basically simulator is not launched automatically when I run "rake" command. That means its stucked on "iphone example.js"...

Please check this very short video http://cl.ly/1h1f473r2f2f0C2j060f of running rake with --trace.

I am using:
bwoken 1.0.0
ruby 1.9.3 (using rvm)
Xcode 4.3.3 (with command line tools installed)
Mac OS X 10.7.4

**Comment by Jaym3s** [comment]
A number of things can cause this.
1. Xcode has a popup asking you to authorize the computer for development. Oftentimes this is a pop-under and on some computers I have seen this not popup at all.
2. If the unix_instruments.sh script bwoken uses exits abnormally it will not properly release it's tty pair, then running it again (in the test phase) can cause it to hang.
3. UIAutomation/command line tools can just be weird sometimes.

Restarting can 'fix' these issues.

**Comment by listrophy** [comment]
Hey @Jaym3s, I believe @jonathanpenn has an updated version of unix_instruments.sh that "fixes" the tty/pty lock in some cases. Let's make sure bwoken has the latest version of the script.

**Comment by jonathanpenn** [comment]
Indeed, it is more robust now. Use this version:

https://gist.github.com/1402258

I'm using signal traps to enforce that the script cleans up and closes the tty/pty pair properly. Let me know if you encounter any more problems. I'm keeping it up to date with any new contingencies to handle.

**Comment by Jaym3s** [comment]
10244d251e567ec0f7990fe9e96e88bcf10656f5 pulls in new unix_instroments @Snekatis Try master and let us know if you continue to have problems!

**Comment by Snekatis** [comment]
Thanks to you for your replies. Bwoken is now working correctly.

**Comment by Jaym3s** [comment]
Glad to hear it!
