### ISSUE TITLE
Is it possible to run bwoken directly on the iOS device?

### ISSUE THREAD

**Issue by Snekatis** [bendyworks/bwoken#5]
Can you add a support for that? Or are you planning that?

**Comment by listrophy** [comment]
We're working on that today! We've made it happen while hacking around, but the trick is going to be in providing users with a decent way to specify simulator or device.

If you have any suggestions on the user experience of this, please let us know.

**Comment by Jaym3s** [comment]
@Snekatis If you'd like to try it out I think we have it working on the [device_support](/bendyworks/bwoken/tree/device_support) branch.

**Comment by Jaym3s** [comment]
Better yet, this was included in release [1.1.0](/bendyworks/bwoken/tree/v1.1.0)
