### ISSUE TITLE
Travis-CI: Failed to connect to local pid watcher service: (os/kern) failure

### ISSUE THREAD

**Issue by metalshreds** [bendyworks/bwoken#51]
Bwoken works great locally but when the Travis-CI machines try to run the tests I get the error below:

```
Failed to connect to local pid watcher service: (os/kern) failure
```

The project builds and it tests fine but the exit code is still 1 instead of 0

https://travis-ci.org/ARISGames/iOSClient

Do you guys have any suggestions on how to fix this?

Thank you,

P.S. I think this is related to the Authorization prompt when the simulator opens.

http://stackoverflow.com/questions/9476131/is-there-a-way-to-remove-the-authorization-prompt-from-command-line-instances-of

**Comment by listrophy** [comment]
No idea what to do here. :\ Let me know if you figure it out.

Closing because running bwoken on Travis isn't officially supported (yet).
