### ISSUE TITLE
verbose does not print the instruments command

### ISSUE THREAD

**Issue by otusweb** [bendyworks/bwoken#52]
I'm trying to debug why broken won't work when run from jenkins and i would need to see the command that is launching instruments so that i can check that it is correct. 

--verbose option unfortunately does not do this.

Is there a quick way for me to see this in the meantime?

Thanks, olivier

**Comment by listrophy** [comment]
I'm on my iPhone, so I'll give it a shot without my laptop:

Run `vim $(bundle show bwoken)/lib/bwoken/script.rb` and on the final line of the `def cmd` function, directly after the vertical pipe, put: `.tap{|c| puts c}`

## Brevity disclaimer: Sent from my iPhone

bradley grzesiak
principal, bendyworks inc
http://bendyworks.com

**Comment by otusweb** [comment]
Thanks for the command. While this one specifically did not work (i might have missed something in the instructions), changing this:

```
def cmd
      %Q|"#{File.expand_path('../../../bin', __FILE__)}/unix_instruments.sh" \
        #{device_flag} \
        -D "#{self.class.trace_file_path}" \
        -t "#{Bwoken.path_to_automation_template}" \
        "#{app_dir}" \
        #{env_variables_for_cli}|
    end
```

to this:

```
    def cmd
      c = %Q|"#{File.expand_path('../../../bin', __FILE__)}/unix_instruments.sh" \
        #{device_flag} \
        -D "#{self.class.trace_file_path}" \
        -t "#{Bwoken.path_to_automation_template}" \
        "#{app_dir}" \
        #{env_variables_for_cli}|
      puts c
      c
    end
```

did work.

**Comment by dblock** [comment]
This is implemented in https://github.com/bendyworks/bwoken/pull/55.

**Comment by listrophy** [comment]
Closing since this functionality will work once #55 is pulled in (slated for v2.1.0).
