### ISSUE TITLE
blocked on ** BUILD SUCCEEDED **

### ISSUE THREAD

**Issue by danydev** [bendyworks/bwoken#53]
bwoken v2.0.0.beta.3

I followed the instructions, and put my tests on the dir "integration/javascript/ipad", on an existing project.

Then I run sudo bwoken test --verbose
(without sudo I have an error while cleaning about removing a .bundle file)

And it builds succesfully (the last thing that I see on the command line is "*\* BUILD SUCCEEDED **").
The simulator launches, goes to landscape (like if it is launching the app), and the app gets immediately closed, returning to the springboard (it doesn't show the splascreen or anything else).

Does someone know how to solve the problem?.

What I tried:
- Restarted mac (since I read in other issues that sometime it is the only solution)
- Checked that the build files are really created
- Used some params like --scheme and --product-name with the right values, but nothing changed.

**Comment by otusweb** [comment]
Did you check in the build folder that it build the correct scheme. I have had issue where it would build a different scheme and thus not really building the app.

**Comment by danydev** [comment]
Where can I see the scheme used to compile in the build directory?. I don't see any reference to it.

**Comment by otusweb** [comment]
Sorry, i was unclear, what i meant is: Can you check that the app is in the build directory (delete that and rebuild)
Also check that the scheme used to build is the one you expect (I believe it says in the terminal which scheme is used if you turn --verbose on)
Also, did you try restarting your machine?

**Comment by danydev** [comment]
- Yes I had already tried to restart my mac.
- I checked that after deleting files in build directory and then running bwoken, it creates the new build files.
- The scheme used is not on the output (with --verbose), however I don't think that it's the problem.

UPDATE: 
I just tried to create a new (empty) project, and running the default tests on it, and it worked.

The funny thing is that after trying again to launch the tests on my original project (either the default or my tests), bwoken hangs again in the phase "*\* BUILD SUCCEEDED **".
After trying to execute the tests on my original project I'm not able to run the tests anymore on any other project, (same behaviour, blocked after BUILD SUCCEDED message), the only solution is to restart the mac.

I also noted that running tests on my original project, the first time after a reboot produces the message "Simulator session timed out." (it was back to all the windows, so I never noticed it before), after it all gets stuck.
After pressing "ok" I see on the console the following error:
_"Recording cancelled : At least one target failed to launch; aborting run
Instruments Trace Error : Error Domain=com.apple.instruments Code=1 "Error Starting Recording" UserInfo=0x7fc4b18c9770 {NSLocalizedDescription=Error Starting Recording, NSLocalizedRecoverySuggestion=At least one target failed to launch; aborting run}
Instruments Trace Error : Failed to start trace."_

So the question at this point is, what can cause bwoken to hang in this way? It could be some settings on my original project, but I have no idea of what it could be

**Comment by danydev** [comment]
I finally solved it, after A LOT of restarts, I figured out that the culprit was "sudo".

Running bwoken with sudo, leads the simulator to hang when executed.

I initially used sudo because I had a problem while building when it needs to remove a bundle file.
I just run a sudo rm -rdf ./build/\* to "clean" manually, and finally running bwoken doesn't hang!.

**Comment by listrophy** [comment]
@danydev THANK YOU for writing about how you solved this problem. I hope it helps many others! I'll also be putting some warnings into the README.
