### ISSUE TITLE
XCode 4.5 support

### ISSUE THREAD

**Issue by ploddi** [bendyworks/bwoken#6]
It seems like paths to /Developer and Instruments hardcoded somewhere in gem, so xcode-select switch cause build to fail.

Can you please add 4.5 support!

**Comment by listrophy** [comment]
OK. It's in our queue of tasks.

Hopefully it will be as simple as respecting `xcode-select`, and doesn't require any more special configuration when calling out to `xcodebuild` or `instruments`.

**Comment by listrophy** [comment]
We'll probably release a new tiny version tomorrow with this fix. Needs a quick look from @Jaym3s, methinks.
