### ISSUE TITLE
Path not found for simulator

### ISSUE THREAD

**Issue by ryanjm** [bendyworks/bwoken#63]
When I try to use the simulator it does a pop up that says:

> Path not found 'Users/ryanjm/code/myAppName/iphone/build/iphonesimulator/MyAppName.app'

Any ideas? With their being multiple iOS versions for the simulator can we pass additional preferences to `--simulator`?

**Comment by listrophy** [comment]
What is the command you used to trigger this?

Also, it seems that there's a missing `/` in front of Users...

**Comment by ryanjm** [comment]
The popup is disappearing quickly today, but you are right, I was missing `/`.

![screen shot 2014-03-12 at 8 59 58 am](https://f.cloud.github.com/assets/90015/2398602/135a389c-a9f7-11e3-867e-4edae370b821.png)

Here is the command I'm doing:

```
% bwoken test --skip-build --verbose  --focus InspectionTests --simulator
File Doesn't Exist, Will Create: /Users/ryanjm/code/orangeqc/iphone/build/iphonesimulator/OrangeQC.app/Info.plist
Delete: Entry, ":UIDeviceFamily", Does Not Exist
File Doesn't Exist, Will Create: /Users/ryanjm/code/orangeqc/iphone/build/iphonesimulator/OrangeQC.app/Info.plist
File Doesn't Exist, Will Create: /Users/ryanjm/code/orangeqc/iphone/build/iphonesimulator/OrangeQC.app/Info.plist
File Doesn't Exist, Will Create: /Users/ryanjm/code/orangeqc/iphone/build/iphonesimulator/OrangeQC.app/Info.plist
Delete: Entry, ":UIDeviceFamily", Does Not Exist
File Doesn't Exist, Will Create: /Users/ryanjm/code/orangeqc/iphone/build/iphonesimulator/OrangeQC.app/Info.plist
File Doesn't Exist, Will Create: /Users/ryanjm/code/orangeqc/iphone/build/iphonesimulator/OrangeQC.app/Info.plist
2014-03-12 08:59:45.177 instruments[17816:1007] Argument 'UIASCRIPT' does not point to a valid script. Using script defined in template.
```

I run my tests on the device just by removing `--simulator`. I have the simulator open with the most recently compiled version of my app.

**Comment by listrophy** [comment]
Try without the `--skip-build` option.

**Comment by ryanjm** [comment]
It does open the simulator now, but it isn't running any tests. Just looks like it freezes on the splash screen.

It selects the 64-bit version of the simulator by default. Any way to pass options to select one of the other simulators? I get a failed build right now when I try to compile for 64-bit in XCode. Though Bwoken says that the build succeeded.

**Comment by listrophy** [comment]
There may be an OS X dialog that pops under your other windows asking for permission to run.

I'm not sure if there's a way to select between the 64-bit simulator or the 32-bit simulator. Obviously, that's a newer feature to Xcode, and I'm confident I haven't yet purposefully addressed this yet... though the functionality might accidentally already be there. If you can figure it out, PRs are more than welcome!

And, as much as it pains me to suggest this, you might consider rebooting your computer.

**Comment by dnnyg33** [comment]
Were you able to figure out the issue? I am also having an issue where, if the simulator flag is set, it will print the name of the test in terminal, launch the simulator (64bit) and then terminal immediately exits the process as if the test completed. However terminal does not print that the test was started or any of the test steps, and the simulator hangs on the splash screen.
If i run this same line without the --simulator, everything works on the device as it should. If i remove the --skip-build, it first builds ("Build Successful") and then does all the same things.

![screen shot 2014-06-11 at 10 55 12 am](https://cloud.githubusercontent.com/assets/3643898/3247909/4021e224-f189-11e3-9a60-9860765c3d19.png)

Any ideas? Thanks

**Comment by ryanjm** [comment]
Sorry, I paused my testing with Bwoken as I catch up on some other development. I believe last time I did it I was still having issues.

**Comment by enrigalmig** [comment]
I solved that problem setting the  --scheme and --product-name
