### ISSUE TITLE
Have Problem Running Bwoken in Jenkins CI

### ISSUE THREAD

**Issue by allenwei** [bendyworks/bwoken#7]
bwoken just stuck  there because of following error:

```
bin/unix_instruments.sh: line 54: /dev/ptyvf: Resource busy
```

Anything I can do to solve it?

Thanks

**Comment by listrophy** [comment]
Currently, our best advice is to restart the machine (or stop the process that is using /dev/ptyvf).

Pull requests welcome to dynamically determine which pty/tty pair to use based on system availability. :)
