### ISSUE TITLE
--family should indicate connected device as well

### ISSUE THREAD

**Issue by jdhovland** [bendyworks/bwoken#72]
I have an iPad and an iPhone connected and I want to set it up so it can test on both devices. "bwoken test" and all variants of "--family=" run only against the first connected device. I'm including a screenshot of an attempt to test against the attached iPhone, with "bwoken test --family=iphone" and it executing against the iPad instead. Thanks.
![bwoken](https://cloud.githubusercontent.com/assets/1153983/3235223/f3efb3da-f0d0-11e3-9972-0af57e04b12c.jpg)

**Comment by listrophy** [comment]
Closing, since I extracted this issue into #77 and #78.
