### ISSUE TITLE
Install & configure bwoken in different folder

### ISSUE THREAD

**Issue by tonyhex** [bendyworks/bwoken#74]
Hello,

May be I missed it while reading docs, but...
How can I install bwoken and it's folders structure in different folder, not in root folder (that contains .xproject file)

Thanks.

**Comment by listrophy** [comment]
Specify `--integration-path` when running bwoken. See https://github.com/bendyworks/bwoken/blob/master/lib/bwoken/cli.rb#L31

This is also mentioned in the README.
