### ISSUE TITLE
Error Parsing imports from file

### ISSUE THREAD

**Issue by arjunjh10** [bendyworks/bwoken#85]
Hello,
i have been trying to build my automation test suite using instruments and bwoken.
Lately I was using Simulator to build scripts and all seemed to work fine. 
I ran my scripts using Bwoken today and got this error:
I have no clue what is wrong here. Can anyone please help me?

 bwoken test --skip-build --integration-path="Testing/"

ipad    check-register-closures.js
WebKit  Threading Violation - initial use of WebKit from a secondary thread.
Error   parsing imports from file on line 1 of check-register-closures.js
Error:  Can't find variable: startTest
Fail:   Test Case failed

Complete
 Duration: 3.685164s

/Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/gems/bwoken-2.1.0.rc.2/lib/bwoken/script.rb:60:in `block in run': Test Script Failed (Bwoken::ScriptFailedError)
    from /Users/arjunjhawar/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/open3.rb:217:in`popen_run'
    from /Users/arjunjhawar/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/open3.rb:99:in `popen3'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/gems/bwoken-2.1.0.rc.2/lib/bwoken/script.rb:58:in`run'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/gems/bwoken-2.1.0.rc.2/lib/bwoken/device_runner.rb:18:in `each'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/gems/bwoken-2.1.0.rc.2/lib/bwoken/device_runner.rb:18:in`execute'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/gems/bwoken-2.1.0.rc.2/lib/bwoken/script_runner.rb:57:in `execute_on_device'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/gems/bwoken-2.1.0.rc.2/lib/bwoken/script_runner.rb:23:in`execute'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/gems/bwoken-2.1.0.rc.2/lib/bwoken/cli/test.rb:114:in `test'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/gems/bwoken-2.1.0.rc.2/lib/bwoken/cli/test.rb:72:in`run'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/gems/bwoken-2.1.0.rc.2/lib/bwoken/cli.rb:58:in `<top (required)>'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/gems/bwoken-2.1.0.rc.2/bin/bwoken:3:in`require'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/gems/bwoken-2.1.0.rc.2/bin/bwoken:3:in `<top (required)>'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/bin/bwoken:23:in`load'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/bin/bwoken:23:in `<main>'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in`eval'
    from /Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `<main>'
rake aborted!
Command failed with status (1): [ bwoken test --skip-build --integration-pa...]
/Users/arjunjhawar/development/VendRegister/Rakefile:12:in`block (2 levels) in <top (required)>'
/Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `eval'
/Users/arjunjhawar/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in`<main>'
Tasks: TOP => test:quick
(See full trace by running task with --trace)

**Comment by listrophy** [comment]
> Error parsing imports from file on line 1 of check-register-closures.js

What does line 1 of `check-register-closures.js` look like?

**Comment by ryanjm** [comment]
@arjunjh10 Is the simulator or device running iOS 7? I had this issue and by changing which device I was using (I was using iPhone 4s simulator with iOS7 and I switched to iPhone 6 with iOS8) this issue went away.

**Comment by arjunjh10** [comment]
Hi, thanks for the reply. I got the problem resolved by moving my tuneup
library into my function library folder. I know its weird but it didnt
throw me any error about tune up initially, and it worked fine as soon as I
moved the tune up.

On 26 November 2014 at 12:38, Ryan Mathews notifications@github.com wrote:

> @arjunjh10 https://github.com/arjunjh10 Is the simulator or device
> running iOS 7? I had this issue and by changing which device I was using (I
> was using iPhone 4s simulator with iOS7 and I switched to iPhone 6 with
> iOS8) this issue went away.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bendyworks/bwoken/issues/85#issuecomment-64491477.

## 

Thanks,
Arjun Jhawar
QA Tester

## 

Watch the fun new 2 minute and 2 second video tour of Vend 
http://youtu.be/zh2X8FyKyMI
